import { fallbackCards } from "@/lib/fallback-cards";
import type { CardFilter, WorldPosition } from "@/lib/types";

export type EditorialCardConfig = {
  cardId: string;
  displayRank: number;
  category: string;
  featuredCategories: CardFilter[];
  editorialSummary: string;
  goodToKnow: string;
  issuerUrl: string;
  ratesAndFeesUrl: string;
  artworkAsset?: string;
  world: WorldPosition;
};

const additionalCards: EditorialCardConfig[] = [
  {
    cardId: "capital-one-venture-x",
    displayRank: 10,
    category: "Premium travel",
    featuredCategories: ["travel", "no-foreign-fee"],
    editorialSummary: "Premium travel perks with a simpler rewards structure.",
    goodToKnow: "The annual fee is easiest to justify when the travel credit and anniversary benefits fit your plans.",
    issuerUrl: "https://www.capitalone.com/credit-cards/venture-x/",
    ratesAndFeesUrl: "https://www.capitalone.com/credit-cards/venture-x/",
    world: { x: 230, y: 250, scale: 0.58, depth: "mid" },
  },
  {
    cardId: "capital-one-savor",
    displayRank: 11,
    category: "Dining and entertainment",
    featuredCategories: ["cash-back", "dining", "groceries", "no-annual-fee", "no-foreign-fee"],
    editorialSummary: "Everyday cash back centered on food and entertainment.",
    goodToKnow: "Compare the bonus categories with where you actually spend most often.",
    issuerUrl: "https://www.capitalone.com/credit-cards/savor/",
    ratesAndFeesUrl: "https://www.capitalone.com/credit-cards/savor/",
    world: { x: 760, y: 40, scale: 0.55, depth: "far" },
  },
  {
    cardId: "capital-one-quicksilver",
    displayRank: 12,
    category: "Cash back",
    featuredCategories: ["cash-back", "no-annual-fee"],
    editorialSummary: "Flat-rate cash back with very little to manage.",
    goodToKnow: "A category card may earn more if your spending is concentrated in a few predictable areas.",
    issuerUrl: "https://www.capitalone.com/credit-cards/quicksilver/",
    ratesAndFeesUrl: "https://www.capitalone.com/credit-cards/quicksilver/",
    world: { x: 1380, y: 480, scale: 0.52, depth: "far" },
  },
  {
    cardId: "citi-strata-premier",
    displayRank: 13,
    category: "Travel",
    featuredCategories: ["travel", "dining", "groceries", "gas", "no-foreign-fee"],
    editorialSummary: "Broad everyday bonus categories that can also support travel.",
    goodToKnow: "Point value depends on how you redeem and whether transfer partners suit you.",
    issuerUrl: "https://www.citi.com/credit-cards/citi-strata-premier-credit-card",
    ratesAndFeesUrl: "https://www.citi.com/credit-cards/citi-strata-premier-credit-card",
    world: { x: 610, y: 900, scale: 0.58, depth: "mid" },
  },
  {
    cardId: "citi-double-cash",
    displayRank: 14,
    category: "Cash back",
    featuredCategories: ["cash-back", "no-annual-fee", "intro-apr"],
    editorialSummary: "A straightforward return on purchases without category tracking.",
    goodToKnow: "Review how rewards are earned and when they become available before comparing headline rates.",
    issuerUrl: "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
    ratesAndFeesUrl: "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
    world: { x: 1260, y: 870, scale: 0.54, depth: "far" },
  },
  {
    cardId: "citi-custom-cash",
    displayRank: 15,
    category: "Cash back",
    featuredCategories: ["cash-back", "dining", "groceries", "gas", "no-annual-fee", "intro-apr"],
    editorialSummary: "Automatically rewards an eligible category where you spend most.",
    goodToKnow: "The top rate is limited by eligible categories and a billing-cycle spending cap.",
    issuerUrl: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    ratesAndFeesUrl: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    world: { x: 420, y: 520, scale: 0.5, depth: "far" },
  },
  {
    cardId: "wells-fargo-active-cash",
    displayRank: 16,
    category: "Cash back",
    featuredCategories: ["cash-back", "no-annual-fee", "intro-apr"],
    editorialSummary: "Flat cash rewards for people who prefer one rate.",
    goodToKnow: "Check foreign transaction fees and redemption rules if you plan to use it while traveling.",
    issuerUrl: "https://creditcards.wellsfargo.com/active-cash-credit-card/",
    ratesAndFeesUrl: "https://creditcards.wellsfargo.com/active-cash-credit-card/",
    world: { x: 930, y: 310, scale: 0.56, depth: "mid" },
  },
  {
    cardId: "wells-fargo-autograph",
    displayRank: 17,
    category: "Travel and everyday",
    featuredCategories: ["travel", "dining", "gas", "no-annual-fee", "no-foreign-fee"],
    editorialSummary: "Several useful everyday categories without an annual fee.",
    goodToKnow: "Transfer and redemption options matter as much as the earning rates.",
    issuerUrl: "https://creditcards.wellsfargo.com/autograph-visa-credit-card/",
    ratesAndFeesUrl: "https://creditcards.wellsfargo.com/autograph-visa-credit-card/",
    world: { x: 50, y: 430, scale: 0.5, depth: "far" },
  },
  {
    cardId: "bank-of-america-customized-cash-rewards",
    displayRank: 18,
    category: "Cash back",
    featuredCategories: ["cash-back", "dining", "gas", "no-annual-fee", "intro-apr"],
    editorialSummary: "Lets you choose a bonus category that fits your routine.",
    goodToKnow: "Quarterly caps and relationship bonuses can materially change the effective return.",
    issuerUrl: "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/",
    ratesAndFeesUrl: "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/",
    world: { x: 760, y: 600, scale: 0.54, depth: "mid" },
  },
  {
    cardId: "bank-of-america-travel-rewards",
    displayRank: 19,
    category: "Travel",
    featuredCategories: ["travel", "no-annual-fee", "no-foreign-fee", "intro-apr"],
    editorialSummary: "Simple travel rewards without an annual fee.",
    goodToKnow: "Redemption flexibility and preferred relationship bonuses determine how competitive it is.",
    issuerUrl: "https://www.bankofamerica.com/credit-cards/products/travel-rewards-credit-card/",
    ratesAndFeesUrl: "https://www.bankofamerica.com/credit-cards/products/travel-rewards-credit-card/",
    world: { x: 1130, y: 510, scale: 0.52, depth: "far" },
  },
  {
    cardId: "discover-it-cash-back",
    displayRank: 20,
    category: "Cash back",
    featuredCategories: ["cash-back", "dining", "groceries", "gas", "no-annual-fee", "no-foreign-fee", "intro-apr"],
    editorialSummary: "Rotating cash-back categories with no annual fee.",
    goodToKnow: "Activation and quarterly spending caps make this more hands-on than a flat-rate card.",
    issuerUrl: "https://www.discover.com/credit-cards/cash-back/it-card.html",
    ratesAndFeesUrl: "https://www.discover.com/credit-cards/cash-back/it-card.html",
    world: { x: 1450, y: 90, scale: 0.48, depth: "far" },
  },
  {
    cardId: "discover-it-student-cash-back",
    displayRank: 21,
    category: "Student cash back",
    featuredCategories: ["cash-back", "no-annual-fee", "no-foreign-fee", "intro-apr"],
    editorialSummary: "A student-focused path into rotating cash-back rewards.",
    goodToKnow: "Approval still depends on underwriting, and the highest rewards require activation.",
    issuerUrl: "https://www.discover.com/credit-cards/student-credit-card/it-card.html",
    ratesAndFeesUrl: "https://www.discover.com/credit-cards/student-credit-card/it-card.html",
    world: { x: 180, y: 850, scale: 0.5, depth: "far" },
  },
  {
    cardId: "amex-blue-cash-preferred",
    displayRank: 22,
    category: "Groceries and cash back",
    featuredCategories: ["cash-back", "groceries", "gas", "intro-apr"],
    editorialSummary: "High grocery rewards for households that can offset the fee.",
    goodToKnow: "The supermarket bonus has eligibility rules and an annual spending cap.",
    issuerUrl: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    ratesAndFeesUrl: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    world: { x: 520, y: 160, scale: 0.5, depth: "far" },
  },
  {
    cardId: "amex-blue-cash-everyday",
    displayRank: 23,
    category: "Everyday cash back",
    featuredCategories: ["cash-back", "groceries", "gas", "no-annual-fee", "intro-apr"],
    editorialSummary: "Everyday bonus categories without an annual fee.",
    goodToKnow: "Category definitions and annual caps are important when comparing expected value.",
    issuerUrl: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/",
    ratesAndFeesUrl: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/",
    world: { x: 1020, y: 930, scale: 0.5, depth: "far" },
  },
  {
    cardId: "amex-platinum",
    displayRank: 24,
    category: "Premium travel",
    featuredCategories: ["travel", "no-foreign-fee"],
    editorialSummary: "A benefits-heavy travel card that rewards careful credit use.",
    goodToKnow: "Its value depends on using several credits and travel benefits that have separate terms.",
    issuerUrl: "https://www.americanexpress.com/us/credit-cards/card/platinum/",
    ratesAndFeesUrl: "https://www.americanexpress.com/us/credit-cards/card/platinum/",
    world: { x: 1320, y: 710, scale: 0.56, depth: "mid" },
  },
  {
    cardId: "amex-green",
    displayRank: 25,
    category: "Travel",
    featuredCategories: ["travel", "dining", "no-foreign-fee"],
    editorialSummary: "Travel and dining rewards with a lighter premium footprint.",
    goodToKnow: "Review the credits and redemption options before deciding whether the annual fee fits.",
    issuerUrl: "https://www.americanexpress.com/us/credit-cards/card/green/",
    ratesAndFeesUrl: "https://www.americanexpress.com/us/credit-cards/card/green/",
    world: { x: 340, y: 1040, scale: 0.48, depth: "far" },
  },
  {
    cardId: "us-bank-altitude-connect",
    displayRank: 26,
    category: "Travel",
    featuredCategories: ["travel", "gas", "no-annual-fee", "no-foreign-fee"],
    editorialSummary: "Travel-oriented categories without an annual fee.",
    goodToKnow: "Point value can depend on how rewards are redeemed, so compare using dollars rather than points alone.",
    issuerUrl: "https://www.usbank.com/credit-cards/altitude-connect-visa-signature-credit-card.html",
    ratesAndFeesUrl: "https://www.usbank.com/credit-cards/altitude-connect-visa-signature-credit-card.html",
    world: { x: 850, y: 820, scale: 0.48, depth: "far" },
  },
  {
    cardId: "us-bank-cash-plus",
    displayRank: 27,
    category: "Cash back",
    featuredCategories: ["cash-back", "no-annual-fee", "intro-apr"],
    editorialSummary: "Customizable bonus categories for people willing to choose them.",
    goodToKnow: "Selections, eligible purchases, and quarterly caps require ongoing attention.",
    issuerUrl: "https://www.usbank.com/credit-cards/cash-plus-visa-signature-credit-card.html",
    ratesAndFeesUrl: "https://www.usbank.com/credit-cards/cash-plus-visa-signature-credit-card.html",
    world: { x: 1180, y: 1030, scale: 0.46, depth: "far" },
  },
  {
    cardId: "bilt-mastercard",
    displayRank: 28,
    category: "Rent and travel",
    featuredCategories: ["travel", "dining", "no-annual-fee", "no-foreign-fee"],
    editorialSummary: "Rewards on rent without the usual card transaction fee.",
    goodToKnow: "Earning rules, transaction minimums, and the card program's current terms deserve a close read.",
    issuerUrl: "https://www.biltrewards.com/card",
    ratesAndFeesUrl: "https://www.biltrewards.com/card",
    world: { x: 20, y: 30, scale: 0.46, depth: "far" },
  },
];

const fallbackConfigs: EditorialCardConfig[] = fallbackCards.map((card, index) => ({
  cardId: card.id,
  displayRank: index + 1,
  category: card.category,
  featuredCategories: card.filters,
  editorialSummary: card.editorialSummary,
  goodToKnow: card.goodToKnow,
  issuerUrl: card.issuerUrl,
  ratesAndFeesUrl: card.ratesAndFeesUrl,
  artworkAsset: card.artworkUrl,
  world: card.world,
}));

export const editorialCardCatalog = [...fallbackConfigs, ...additionalCards]
  .sort((first, second) => first.displayRank - second.displayRank);
