import type { Card } from "@/lib/types";

const verifiedAt = "2026-07-31T12:00:00.000Z";

const fallbackCardDefinitions: Array<Omit<Card, "dataSource">> = [
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred®",
    shortName: "Sapphire Preferred",
    issuer: "Chase",
    network: "Visa",
    category: "Travel",
    annualFee: 95,
    annualFeeLabel: "$95",
    foreignTransactionFee: "$0",
    purchaseApr: "19.24%–27.49% variable",
    welcomeOffer: {
      amount: "75,000 pts",
      requirement: "After qualifying purchases; verify the current issuer offer.",
    },
    rewardRates: [
      { category: "dining", label: "Dining", rate: 3, type: "multiplier" },
      { category: "travel", label: "Other travel", rate: 2, type: "multiplier" },
    ],
    rewardSummary: "3× dining · 2× travel",
    benefits: ["Flexible points", "Travel protections", "Transfer partners"],
    applicationRules: ["Approval and offer eligibility are determined by the issuer."],
    editorialSummary: "Easy to understand and broadly useful.",
    goodToKnow: "Points can transfer to airline and hotel partners. Offer terms and eligibility rules apply.",
    filters: ["travel", "dining", "no-foreign-fee"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire-preferredcard2026.png",
    issuerUrl: "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred",
    ratesAndFeesUrl: "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred",
    updatedAt: verifiedAt,
    world: { x: 535, y: 350, scale: 1, depth: "near" },
  },
  {
    id: "amex-gold",
    name: "American Express® Gold Card",
    shortName: "Amex Gold",
    issuer: "American Express",
    network: "American Express",
    category: "Dining",
    annualFee: 325,
    annualFeeLabel: "$325",
    foreignTransactionFee: "$0",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "dining", label: "Restaurants", rate: 4, type: "multiplier" },
      { category: "groceries", label: "U.S. supermarkets", rate: 4, type: "multiplier" },
    ],
    rewardSummary: "4× dining · 4× groceries",
    benefits: ["Dining credits", "Uber Cash", "Hotel Collection credit"],
    applicationRules: ["Enrollment and benefit terms apply."],
    editorialSummary: "Strong food rewards with credits to keep track of.",
    goodToKnow: "The value depends on whether the included credits fit your normal spending.",
    filters: ["travel", "dining", "groceries", "no-foreign-fee"],
    artworkUrl:
      "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/gold-card.png",
    issuerUrl: "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    ratesAndFeesUrl: "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    updatedAt: verifiedAt,
    world: { x: -40, y: 125, scale: 0.72, depth: "mid" },
  },
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve®",
    shortName: "Sapphire Reserve",
    issuer: "Chase",
    network: "Visa",
    category: "Premium travel",
    annualFee: 795,
    annualFeeLabel: "$795",
    foreignTransactionFee: "$0",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "travel", label: "Chase Travel", rate: 8, type: "multiplier" },
      { category: "dining", label: "Dining", rate: 3, type: "multiplier" },
    ],
    rewardSummary: "8× Chase Travel · 3× dining",
    benefits: ["Travel credit", "Airport lounge access", "Travel protections"],
    applicationRules: ["Premium benefits and credit terms apply."],
    editorialSummary: "A premium travel card with a premium price.",
    goodToKnow: "The annual fee only makes sense when the credits and travel benefits are used consistently.",
    filters: ["travel", "dining", "no-foreign-fee"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_reserve_card_Halo.png",
    issuerUrl: "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve",
    ratesAndFeesUrl: "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve",
    updatedAt: verifiedAt,
    world: { x: 1210, y: 150, scale: 0.75, depth: "mid" },
  },
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited®",
    shortName: "Freedom Unlimited",
    issuer: "Chase",
    network: "Visa",
    category: "Cash back",
    annualFee: 0,
    annualFeeLabel: "$0",
    foreignTransactionFee: "3%",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "dining", label: "Dining", rate: 3, type: "cashback_percent" },
      { category: "other", label: "All other purchases", rate: 1.5, type: "cashback_percent" },
    ],
    rewardSummary: "3% dining · 1.5% other",
    benefits: ["No annual fee", "Simple base rewards", "Purchase protection"],
    applicationRules: ["Introductory APR and offer eligibility vary."],
    editorialSummary: "Simple cash back without an annual fee.",
    goodToKnow: "Foreign transaction fees make it less useful for purchases abroad.",
    filters: ["cash-back", "dining", "no-annual-fee", "intro-apr"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/freedom_unlimited_card_alt.png",
    issuerUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
    ratesAndFeesUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
    updatedAt: verifiedAt,
    world: { x: 80, y: 650, scale: 0.78, depth: "mid" },
  },
  {
    id: "world-of-hyatt",
    name: "World of Hyatt Credit Card",
    shortName: "World of Hyatt",
    issuer: "Chase",
    network: "Visa",
    category: "Hotel travel",
    annualFee: 95,
    annualFeeLabel: "$95",
    foreignTransactionFee: "$0",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "hotels", label: "Hyatt stays", rate: 4, type: "multiplier" },
      { category: "travel", label: "Transit", rate: 2, type: "multiplier" },
    ],
    rewardSummary: "4× Hyatt · 2× transit",
    benefits: ["Annual free night", "Hyatt Discoverist status", "Bonus qualifying nights"],
    applicationRules: ["Hyatt and issuer program terms apply."],
    editorialSummary: "Most useful for people who already choose Hyatt.",
    goodToKnow: "Hotel points are less flexible than general travel rewards.",
    filters: ["travel", "no-foreign-fee"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/world_of_hyatt_card.png",
    issuerUrl: "https://creditcards.chase.com/travel-credit-cards/world-of-hyatt-credit-card",
    ratesAndFeesUrl: "https://creditcards.chase.com/travel-credit-cards/world-of-hyatt-credit-card",
    updatedAt: verifiedAt,
    world: { x: 1110, y: 685, scale: 0.8, depth: "mid" },
  },
  {
    id: "marriott-bonvoy-boundless",
    name: "Marriott Bonvoy Boundless® Credit Card",
    shortName: "Marriott Boundless",
    issuer: "Chase",
    network: "Visa",
    category: "Hotel travel",
    annualFee: 95,
    annualFeeLabel: "$95",
    foreignTransactionFee: "$0",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "hotels", label: "Marriott stays", rate: 6, type: "multiplier" },
      { category: "other", label: "Other purchases", rate: 2, type: "multiplier" },
    ],
    rewardSummary: "6× Marriott · 2× other",
    benefits: ["Annual free night", "Automatic elite night credits", "Silver Elite status"],
    applicationRules: ["Marriott and issuer program terms apply."],
    editorialSummary: "A straightforward companion for Marriott stays.",
    goodToKnow: "The annual free night is the main reason to keep the card long term.",
    filters: ["travel", "no-foreign-fee"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/marriott-bonvoy-boundless-card.png",
    issuerUrl: "https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/boundless",
    ratesAndFeesUrl: "https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/boundless",
    updatedAt: verifiedAt,
    world: { x: 300, y: -25, scale: 0.68, depth: "far" },
  },
  {
    id: "southwest-rapid-rewards-plus",
    name: "Southwest Rapid Rewards® Plus Credit Card",
    shortName: "Southwest Plus",
    issuer: "Chase",
    network: "Visa",
    category: "Airline travel",
    annualFee: 99,
    annualFeeLabel: "$99",
    foreignTransactionFee: "$0",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "travel", label: "Southwest purchases", rate: 2, type: "multiplier" },
      { category: "transit", label: "Local transit", rate: 2, type: "multiplier" },
    ],
    rewardSummary: "2× Southwest · 2× transit",
    benefits: ["Anniversary points", "Checked bag benefits", "Seat selection benefits"],
    applicationRules: ["Southwest and issuer program terms apply."],
    editorialSummary: "A practical entry card for regular Southwest flyers.",
    goodToKnow: "Airline-specific rewards are best when Southwest already fits your travel patterns.",
    filters: ["travel", "no-foreign-fee"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/swa_plus_card_New.png",
    issuerUrl: "https://creditcards.chase.com/travel-credit-cards/southwest/plus",
    ratesAndFeesUrl: "https://creditcards.chase.com/travel-credit-cards/southwest/plus",
    updatedAt: verifiedAt,
    world: { x: 880, y: 1010, scale: 0.72, depth: "far" },
  },
  {
    id: "chase-freedom-flex",
    name: "Chase Freedom Flex®",
    shortName: "Freedom Flex",
    issuer: "Chase",
    network: "Mastercard",
    category: "Cash back",
    annualFee: 0,
    annualFeeLabel: "$0",
    foreignTransactionFee: "3%",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "rotating", label: "Rotating categories", rate: 5, type: "cashback_percent" },
      { category: "dining", label: "Dining", rate: 3, type: "cashback_percent" },
    ],
    rewardSummary: "5% rotating · 3% dining",
    benefits: ["No annual fee", "Rotating bonus categories", "Cell phone protection"],
    applicationRules: ["Quarterly category activation and spending caps apply."],
    editorialSummary: "High category rewards if you do not mind activating them.",
    goodToKnow: "The highest rate is capped and changes each quarter.",
    filters: ["cash-back", "dining", "gas", "no-annual-fee", "intro-apr"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/freedom_flex_card_alt.png",
    issuerUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex",
    ratesAndFeesUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex",
    updatedAt: verifiedAt,
    world: { x: -50, y: 1000, scale: 0.72, depth: "far" },
  },
  {
    id: "chase-freedom-rise",
    name: "Chase Freedom Rise®",
    shortName: "Freedom Rise",
    issuer: "Chase",
    network: "Visa",
    category: "Starter cash back",
    annualFee: 0,
    annualFeeLabel: "$0",
    foreignTransactionFee: "3%",
    purchaseApr: "See rates & fees",
    welcomeOffer: { amount: "See current offer" },
    rewardRates: [
      { category: "other", label: "All purchases", rate: 1.5, type: "cashback_percent" },
    ],
    rewardSummary: "1.5% cash back",
    benefits: ["No annual fee", "Simple rewards", "Automatic credit line review"],
    applicationRules: ["Approval remains subject to issuer underwriting."],
    editorialSummary: "A simple starting point for building credit history.",
    goodToKnow: "Its rewards are uncomplicated, but it charges a foreign transaction fee.",
    filters: ["cash-back", "no-annual-fee"],
    artworkUrl:
      "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/freedom_rise_alt_card2.png",
    issuerUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/rise",
    ratesAndFeesUrl: "https://creditcards.chase.com/cash-back-credit-cards/freedom/rise",
    updatedAt: verifiedAt,
    world: { x: 1040, y: -20, scale: 0.7, depth: "far" },
  },
];

export const fallbackCards: Card[] = fallbackCardDefinitions.map((card) => ({
  ...card,
  dataSource: "editorial-fallback",
}));
